### ISSUE TITLE
Problem in the WebSecurityConfigurerAdapter

### ISSUE THREAD

**Issue by SergioRt1** [dnielben/spring-mvc-jwt#1]
must uncomment line that enables the POST method so that it is possible to register a user in /users/sign-up
`.antMatchers(HttpMethod.POST, SIGN_UP_URL).permitAll()`
It would be nice if you could register from the test page, this can be done adding to the JS

' function signUp() {

    axios.post('/users/sign-up', {
        "username": "admin",
        "password": "password"
    })
        .then(function (response) {
            console.log(response);
        })
        .catch(function (reason) {
            console.log(reason);
        })
    document.getElementById("register").setAttribute('disabled',true);
}  '

and in html
`<button id="register" type="button" onclick="signUp()">Register</button>`

PD: token is in response.headers.authorization

**Comment by dnielben** [comment]
The idea is that users can modify the JS to create a complete test, as if they were testing from the command line.  I will complete the test in the future so the interaction can be seen from the web page.
